# Temperature converter 

Complete the following program that converts temperature from degree F to degree C

The output for the example is left on the notebook for your reference

The formual for conversion is $ C = (F − 32) × 5/9  $

In [1]:
print("Enter temperature in degree F:")
temp_f = input()

Enter temperature in degree F:

 66

In [2]:
temp_f = float(temp_f)
temp_c = (temp_f - 32) * 5 / 9
print(f"The temprature in degree C is {temp_c:.2f}")

The temprature in degree C is 18.89

# Temperature converter in English

Modify the above program to accept in put in English, for example instead of `66`, the user enters `sixty six`

Assume that the valid range of values is zero to ninety nine

In [3]:
print("Enter temperature in degree F:")
temp_f = input()

Enter temperature in degree F:

 sixty

In [4]:
#hint use this dict
letter2number = {'zero':0, 'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8, 'nine':9,
                'ten':10, 'twenty':20, 'thirty':30, 'forty':40, 'fifty':50, 'sixty':60, 'seventy':70, 'eighty':80, 'ninety':90}

In [5]:
comps = temp_f.lower().split()
temp_f = sum( letter2number[comp] for comp in comps )
temp_c = (temp_f - 32) * 5 / 9
print(f"The temprature in degree C is {temp_c:.2f}")

The temprature in degree C is 15.56

# Comprehensions

In [6]:
# us states names
states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

# us states abbreviations
states_abbrev = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

Create a dictionary to map each state to its abbreviation

In [7]:
state_aberv = {states[i]:states_abbrev[i] for i in range(len(states)) }
state_aberv

{'Alabama': 'AL',
 'Alaska': 'AK',
 'Arizona': 'AZ',
 'Arkansas': 'AR',
 'California': 'CA',
 'Colorado': 'CO',
 'Connecticut': 'CT',
 'Delaware': 'DE',
 'Florida': 'FL',
 'Georgia': 'GA',
 'Hawaii': 'HI',
 'Idaho': 'ID',
 'Illinois': 'IL',
 'Indiana': 'IN',
 'Iowa': 'IA',
 'Kansas': 'KS',
 'Kentucky': 'KY',
 'Louisiana': 'LA',
 'Maine': 'ME',
 'Maryland': 'MD',
 'Massachusetts': 'MA',
 'Michigan': 'MI',
 'Minnesota': 'MN',
 'Mississippi': 'MS',
 'Missouri': 'MO',
 'Montana': 'MT',
 'Nebraska': 'NE',
 'Nevada': 'NV',
 'New Hampshire': 'NH',
 'New Jersey': 'NJ',
 'New Mexico': 'NM',
 'New York': 'NY',
 'North Carolina': 'NC',
 'North Dakota': 'ND',
 'Ohio': 'OH',
 'Oklahoma': 'OK',
 'Oregon': 'OR',
 'Pennsylvania': 'PA',
 'Rhode Island': 'RI',
 'South Carolina': 'SC',
 'South Dakota': 'SD',
 'Tennessee': 'TN',
 'Texas': 'TX',
 'Utah': 'UT',
 'Vermont': 'VT',
 'Virginia': 'VA',
 'Washington': 'WA',
 'West Virginia': 'WV',
 'Wisconsin': 'WI',
 'Wyoming': 'WY'}

In [8]:
dict(zip(states, states_abbrev))

{'Alabama': 'AL',
 'Alaska': 'AK',
 'Arizona': 'AZ',
 'Arkansas': 'AR',
 'California': 'CA',
 'Colorado': 'CO',
 'Connecticut': 'CT',
 'Delaware': 'DE',
 'Florida': 'FL',
 'Georgia': 'GA',
 'Hawaii': 'HI',
 'Idaho': 'ID',
 'Illinois': 'IL',
 'Indiana': 'IN',
 'Iowa': 'IA',
 'Kansas': 'KS',
 'Kentucky': 'KY',
 'Louisiana': 'LA',
 'Maine': 'ME',
 'Maryland': 'MD',
 'Massachusetts': 'MA',
 'Michigan': 'MI',
 'Minnesota': 'MN',
 'Mississippi': 'MS',
 'Missouri': 'MO',
 'Montana': 'MT',
 'Nebraska': 'NE',
 'Nevada': 'NV',
 'New Hampshire': 'NH',
 'New Jersey': 'NJ',
 'New Mexico': 'NM',
 'New York': 'NY',
 'North Carolina': 'NC',
 'North Dakota': 'ND',
 'Ohio': 'OH',
 'Oklahoma': 'OK',
 'Oregon': 'OR',
 'Pennsylvania': 'PA',
 'Rhode Island': 'RI',
 'South Carolina': 'SC',
 'South Dakota': 'SD',
 'Tennessee': 'TN',
 'Texas': 'TX',
 'Utah': 'UT',
 'Vermont': 'VT',
 'Virginia': 'VA',
 'Washington': 'WA',
 'West Virginia': 'WV',
 'Wisconsin': 'WI',
 'Wyoming': 'WY'}

#  Data processing practice

Select records where the value is not `"GREEN"`

In [9]:
records = ["RED", "BLUE", "BLUE", "GREEN", "RED"]

In [10]:
[record for record in records if record != "GREEN"]

['RED', 'BLUE', 'BLUE', 'RED']

Select records of products from China

In [11]:
# sample records of products, each product has a name, price, and country of origin
records = [{'name': 'office chair', 'price': 150, 'coo':'China'},
           {'name': 'bike', 'price': 800, 'coo': 'China'},
           {'name': 'car', 'price': 40000, 'coo': 'Germany'},
           {'name': 'laptop', 'price': 2000, 'coo': 'USA'},
           {'name': 'desk', 'price': 300, 'coo': 'China'},
           {'name': 'lamp', 'price': 50, 'coo': 'China'}]

In [12]:
[record for record in records if record['coo'] == 'China']

[{'name': 'office chair', 'price': 150, 'coo': 'China'},
 {'name': 'bike', 'price': 800, 'coo': 'China'},
 {'name': 'desk', 'price': 300, 'coo': 'China'},
 {'name': 'lamp', 'price': 50, 'coo': 'China'}]

What is the most expensive product?

In [13]:
highest_price = max(record['price'] for record in records)
[record for record in records if record['price'] == highest_price][0]

{'name': 'car', 'price': 40000, 'coo': 'Germany'}

What is the most expensive product from China?

In [14]:
highest_price = max(record['price'] for record in records if record['coo'] == 'China')
[record for record in records if record['price'] == highest_price][0]

{'name': 'bike', 'price': 800, 'coo': 'China'}

In [15]:
records = [('office chair', 150, 'China'),
           ('bike', 800, 'China'),
           ('car', 40000, 'Germany'),
           ('laptop', 2000, 'USA'),
           ('desk', 300, 'China'),
           ('lamp', 50, 'China')]

- Select records of products from China
- What is the most expensive product?
- What is the most expensive product from China?

In [16]:
[record for record in records if record[2] == 'China']

[('office chair', 150, 'China'),
 ('bike', 800, 'China'),
 ('desk', 300, 'China'),
 ('lamp', 50, 'China')]

In [17]:
highest_price = max(record[1] for record in records)
[record for record in records if record[1] == highest_price][0]

('car', 40000, 'Germany')

In [18]:
# using sorted
sorted(records, key=lambda record: record[1], reverse=True)[0]

('car', 40000, 'Germany')

In [19]:
# What is the most expensive product from China?
highest_price = max(record[1] for record in records if record[2] == 'China')
[record for record in records if record[1] == highest_price][0]

('bike', 800, 'China')

In [20]:
import pandas as pd
df = pd.DataFrame(records, columns=['name', 'price', 'coo'])
df

           name  price      coo
0  office chair    150    China
1          bike    800    China
2           car  40000  Germany
3        laptop   2000      USA
4          desk    300    China
5          lamp     50    China

- Select records of products from China
- What is the most expensive product?
- What is the most expensive product from China?

In [21]:
df[df.coo=='China']

           name  price    coo
0  office chair    150  China
1          bike    800  China
4          desk    300  China
5          lamp     50  China

In [22]:
df.sort_values('price', ascending=False).iloc[0]

name         car
price      40000
coo      Germany
Name: 2, dtype: object

In [23]:
df[df.coo=='China'].sort_values('price', ascending=False).iloc[0]

name      bike
price      800
coo      China
Name: 1, dtype: object